run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Find unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Find misspellings
    - gocritic      # Opinionated linter

linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - io.ReadAll
      - (*os/exec.Cmd).StderrPipe
      - (*net/http.Response.Body).Close
      - (io.Closer).Close
      - os.Setenv
      - fmt.Sscanf
  gocritic:
    enabled-tags:
      - diagnostic
    disabled-checks:
      - ifElseChain
  misspell:
    locale: US
    ignore-words:
      - cancelled  # Used by GitHub/Gitea APIs

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Allow ignored errors for progress reporting (best-effort)
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/orchestrator/
      linters:
        - errcheck
    - path: internal/workflow/
      linters:
        - errcheck
    - path: internal/providers/
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
